### ISSUE TITLE
Weapons bug 

### ISSUE THREAD

**Issue by yiewjo** [NotCoffee418/TrinityCreator#70] opened 2020-01-12 13:18 UTC
Found some following issues:

1: Weapons created, unable to use class skills. 

2: Unable to create bow and equip.

Thx

**Comment by NotCoffee418** [comment] 2020-01-14 03:27
If anyone knows what's causing this or knows which value to modify after item creation to fix weapons, let me know please.

**Comment by illfated** [comment] 2020-01-14 11:54
Unless confirmed already by others besides the OP, could this be caused by not reloading the tables or restarting the server?

**Comment by NotCoffee418** [comment] 2020-01-14 13:14
It's been reported before. Weapons have never been right as far as i know.
I'm guessing people just don't use it for weapons or know what they're doing anyway.
Maybe whatever's causing it is fixed in the new system. Either way, i have working TC install (for the first time in like 3 years lol) so I'll do some testing myself later on.

**Comment by yiewjo** [comment] 2020-01-15 00:01
Thanks guys for the replies, I tried restarting the server but the results are the same. I will try to figure it out later this week and if I come across some answers I’ll post it on.

**Comment by NotCoffee418** [comment] 2020-01-27 10:42
Generic Sword of Testing (Thunderfury modelid)
- [ ] Right click will not equip (drag will)
- [ ] Icon will not appear in bag but will appear when equipped (after cache reset)
- [ ] Multiple gem sockets with the same color will not appear
- [ ] Resistance on item is not added
- [ ] +melee crit not added (invalid?)
- [ ] Invisible when sheathed

![image](https://user-images.githubusercontent.com/9306304/73168332-e880a200-40f9-11ea-9e9c-6da4781e5bc7.png)
![image](https://user-images.githubusercontent.com/9306304/73168351-efa7b000-40f9-11ea-8243-dd80be859164.png)

`INSERT INTO item_template (entry, name, description, class, subclass, Quality, displayid, bonding, RequiredLevel, maxcount, AllowableClass, AllowableRace, BuyPrice, SellPrice, InventoryType, Flags, FlagsExtra, BuyCount, stackable, ContainerSlots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, MaxDurability, socketBonus, StatsCount, armor, block, BagFamily, ItemLevel, RangedModRange, socketColor_1, socketContent_1, socketColor_2, socketContent_2, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3) VALUES (500000, 'Generic Sword of Testing', 'unique,mcrit,int,str,102dur,83dps,1.50,500g,124g,15fres,rrmsock+4strbonus', 2, 8, 0, 30606, 2, 80, 0, -1, -1, 5000000, 1240000, 17, 524288, 0, 1, 1, 0, 100, 150, 1500, 0, 0, 102, 106, 3, 0, 0, 0, 80, 0, '1', '1', '2', '2', '19', '15', '5', '15', '4', '15');
`

**Comment by NotCoffee418** [comment] 2020-01-27 20:13
"In the 3.3.5 client and all expansion after it, there is a list of items which defines what type every item is and how it looks. The game only cares about what type the item is in its own list, not what the server says. So even if you make a new weapon item in your server's database, the game does not let you use any abilities that require a weapon, because there is not such weapon according to its own files. This means the only weapons you can really use are those created by Blizzard. It's easier to just change the stats on an existing weapon, than to bother making a new custom weapon. To make custom weapons, you must modify the items DBC file used by the client and add your new item to it. That is done by a custom MPQ patch, which forces WoW to replace the original file with the one you made." -brotalnia Ownedcore

**Comment by NotCoffee418** [comment] 2020-01-27 22:37
Sadly that commit is the best i can do for wotlk+.
An explanation on why weapons with new IDs dont work and the option to replace an existing weapon with your creation to make it probably work.

**Comment by NotCoffee418** [comment] 2020-01-28 01:27
Some things not being added to the item fixed in 20aeca4e7cec5e5bbf67e6d2a81e5b1690ca3ac0

**Closed by NotCoffee418** 2020-01-28 01:27 UTC
Labels: bug, help wanted
