### ISSUE TITLE
Crash on profile select

### ISSUE THREAD

**Issue by PINNGU** [NotCoffee418/TrinityCreator#93] opened 2020-04-29 19:40 UTC
SO i just downloaded your trinity creator and i cannot start it .Upon choosing profiles when i try to choose one it just crashes and it says it has stopped working...What can i do about it?

**Comment by illfated** [comment] 2020-04-29 20:56
We need more details.
- Which Windows version do you use?
- WoW game client patch version?
- Did you see any crash messages or error messages to write down,
or maybe capture via Alt+PrintScreen, to paste here in a comment?

**Comment by PINNGU** [comment] 2020-04-29 22:20
1.Windows 7 64 Bit
2. 3.3.5a WOTLK
3.
![Screenshot_401](https://user-images.githubusercontent.com/50182860/80652524-64331780-8a78-11ea-9118-43fea588de8b.png)
![Screenshot_402](https://user-images.githubusercontent.com/50182860/80652539-6ac18f00-8a78-11ea-9697-a46db48e203e.png)

**Comment by illfated** [comment] 2020-04-30 17:01
Thank you for the added information. There is an important piece of information here which may help us solve your issue: 
`Problem Signature 09: System.Windows.Markup.XamlParse`

#28 (**Program Crashing Immediately After Being Opened**)
> Changed to only release as 32bit, probably causes issues with CefSharp. ec941724c20155766cdead0d64133be30cec9c0d
> 
> Download the new version:
> https://github.com/Nadromar/TrinityCreator/blob/master/TrinityCreatorSetup/bin/Release/TrinityCreatorSetup.msi?raw=true
> 
> If that doesn't fix it, please let me know.

#18 (**Crashes on launch**)
> Hello,
> 
> Please ensure your PC is Windows 7 or newer have the prerequisites installed:
> https://www.microsoft.com/en-us/download/details.aspx?id=30653
> 
> If this fails, press Ctrl+R and enter "%USERPROFILE%\AppData\Local" and delete a folder called "Nadromar" to reset any faulty settings.

**Comment by illfated** [comment] 2020-04-30 17:04
Regarding the link https://www.microsoft.com/en-us/download/details.aspx?id=30653 (Microsoft .NET Framework 4.5):
> Additional Information
> This version of the .NET Framework runs side-by-side with the .NET Framework 3.5 and earlier versions, but performs an in-place update for the .NET Framework 4.
>
> For important information about this release, see the [.NET Framework 4.5 Readme File](http://go.microsoft.com/fwlink/?LinkId=255964).

**Comment by PINNGU** [comment] 2020-04-30 22:56
I have removed the version i installed(which was the newest one already) ,and installed it again.An update screen has popped upon installation completed,but i didn't accept it.Then i tried to choose a profile and it worked.No crashes now.Will test it out and come back with more information,but the crash might be due to the update?Just wanted to let you know,

**Comment by illfated** [comment] 2020-05-01 09:39
Very good. You may also want to verify that **.NET Framework 4.5** is installed and updated on your computer, to avoid `System.Windows.Markup.XamlParse` errors as much as possible.

**Comment by PINNGU** [comment] 2020-05-01 12:17
First thing that crossed my mind after it was crashing,and when i downloaded it ,it just said i had it already.Probably not the reason,

**Comment by PINNGU** [comment] 2020-05-01 13:35
Hey another error.When i try to create a quest this pops:
![Screenshot_404](https://user-images.githubusercontent.com/50182860/80809150-5d63ec00-8bc1-11ea-8ab8-77313141ce70.png)

**Comment by illfated** [comment] 2020-05-01 16:32
Looks like a mismatch between the TDB used by TrinityCreator and your own TDB version, but I could be mistaken. I hope @NotCoffee418 may get time to post a comment about that.

**Comment by NotCoffee418** [comment] 2020-05-05 13:29
The second error is caused by being on an outdated alpha version that doesn't support the current profiles.

That first issue will be nasty. Someone else has the same issue but I can't reproduce it on a fresh install. 

Could you please upload a log file of a run where this occurred?
1. Press Win+R on your keyboard.
2. Enter `%localappdata%\NotCoffee418\TrinityCreator\Logs` and press OK
3. Upload the file with the matching timestamp here.

Thanks!

**Comment by NotCoffee418** [comment] 2020-05-05 15:49
Fixed in 7502cfd0ea32c1125d1bfeb00a72934e4b9bdb65
Will publish new version & release in a few minutes.

**Closed by NotCoffee418** 2020-05-05 15:49 UTC
