### ISSUE TITLE
TrinityCreator Stopped Working

### ISSUE THREAD

**Issue by commer1337** [NotCoffee418/TrinityCreator#95] opened 2020-05-04 14:24 UTC
**After updating to the latest version, I have the following issue>**

**TrinityCreator.exe>Profile choosing - (Lights Hope, Trinitycore 3.3.5a 2020, Trinitycore 3.3.5a 2016) There is no matter wich one from those 3, when I press Activate to one of them, It comes to "TrinityCreator Stopped Working..... ?**
![изтеглен файл](https://user-images.githubusercontent.com/43073689/80976433-234a5280-8e2c-11ea-8fde-03bf6014b733.png)

**Any help ?**

**Best Regards**

**Comment by NotCoffee418** [comment] 2020-05-05 13:31
Duplicate of #93.
Please also follow the instructions in my last comment there.

**Comment by NotCoffee418** [comment] 2020-05-05 15:48
Fixed in 7502cfd0ea32c1125d1bfeb00a72934e4b9bdb65

**Closed by NotCoffee418** 2020-05-05 15:48 UTC
Labels: duplicate
