### ISSUE TITLE
Vanilla Quest chains

### ISSUE THREAD

**Issue by T1ti** [NotCoffee418/TrinityCreator#114] opened 2020-07-07 18:32 UTC
Currently entering "previous quest" and "next quest" doesn't fill the entry "next questinchain" but only prev/nextquestID. There is no way to currently add data to this column with trinity creator. (vmangos emulator)

**Comment by T1ti** [comment] 2020-07-07 18:34
![image](https://user-images.githubusercontent.com/40864460/86826550-2f06ff00-c091-11ea-9bf3-273f6b5b6efa.png)

**Comment by NotCoffee418** [comment] 2020-07-07 23:18
I don't quite get this field. Does it do anything other than exist? Should it be the same value as NextQuestID?

It could be done using custom fields if it's always the same value.
Quest.NextQuestId - NextQuestInChain - quest_template

I can can also add another field to the UI but I'm not sure if it even does anything.

**Comment by T1ti** [comment] 2020-07-08 17:31
This field makes it so when you complete a quest it automaticaly shows the next quest in the quest chain to the player, without it you just have the normal npc gossip menu with all his different quests. Quest chains might even have more features but I'm not sure. 
I definitely notice the lack of smoothness of quest chains without this

**Comment by NotCoffee418** [comment] 2020-07-09 15:58
Mhm I'll just fix it through profiles then.

**Comment by NotCoffee418** [comment] 2020-07-09 16:43
Fixed in 590994cc8b4e7f7ae692af01e0776f2e3fcf8026 and 9cd97c9d64bfb39ded85ab316aed08a4c19518ad.

Turns out implementing this using custom fields as described above would cause an error caused by validation used by the "Replace existing quest" mechanic introduced recently.
I don't know what it means either. I just drink lots of coffee and type random characters until the code works.

Make sure to update to the latest build.

**Closed by NotCoffee418** 2020-07-09 16:43 UTC
